version: '3.8'

services:
  db:
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      TZ: Asia/Dushanbe
      POSTGRES_DB: telegrambotdb
      POSTGRES_USER: azamat09
      POSTGRES_PASSWORD: Azamat2341!
    ports:
      - "5432:5432"

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./bot/src:/app/src
    environment:
      TZ: Asia/Dushanbe
      NODE_ENV: production
      BOT_TOKEN: 6472872266:AAEEb-BmL1CNCDkCGSqPYeS4Efl-p5-RdRg
      DB_URL: postgresql://azamat09:Azamat2341!@db:5432/telegrambotdb
    depends_on:
      - db

volumes:
  db-data:
